[run]
run = "python deployment_test_server.py"

[deployment]
run = ["python", "deployment_test_server.py"]
deploymentTarget = "autoscale"

[env]
PYTHONPATH = "."

[packager]
language = "python3"

[packager.features]
packageSearch = true
guessImports = true

[languages.python3]
pattern = "**/*.py"
syntax = "python"

[languages.python3.languageServer]
start = ["pylsp"]

[nix]
channel = "stable-24_05"

[gitHubImport]
requiredFiles = [".replit", "replit.toml"]