[run]
run = "python3 main.py"

[deployment]
run = ["python3", "main.py"]
deploymentTarget = "cloudrun"
ignorePorts = false

[nix]
channel = "stable-24_05"

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]
localPort = 5001
externalPort = 3000