[run]
run = "/nix/store/h097imm3w6dpx10qynrd2sz9fks2wbq8-python3-3.12.11/bin/python3 main.py"

[deployment]
run = ["/nix/store/h097imm3w6dpx10qynrd2sz9fks2wbq8-python3-3.12.11/bin/python3", "main.py"]
deploymentTarget = "cloudrun"
ignorePorts = false

[nix]
channel = "stable-24_05"

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]
localPort = 5001
externalPort = 3000